### ISSUE TITLE
这个错误是怎么回事？麻烦了

### ISSUE THREAD

**Issue by elvischao** [thank243/lightsailMon#174]
time="2024-03-10T16:48:35+08:00" level=warning msg="LightsailMon Started"
LightsailMon dev, built at 2024-02-19T15:32:24+00:00
An AWS Lightsail monitor service that can auto change blocked IP.
Log level: warning, Concurrent: 20, DDNS: Cloudflare, Notifier: off
time="2024-03-10T16:50:46+08:00" level=error msg="RequestError: send request failed\ncaused by: Post \"https://lightsail.ap-southeast-1.amazonaws.com/\": dial tcp 54.240.226.245:443: i/o timeout" domain=x1.x.top
time="2024-03-10T16:52:46+08:00" level=error msg="RequestError: send request failed\ncaused by: Post \"https://lightsail.ap-southeast-1.amazonaws.com/\": dial tcp 54.240.226.234:443: i/o timeout" domain=x2.x.top
2024/03/10 16:53:16.457956 WARN RESTY Get "http://connectivitycheck.platform.hicloud.com/generate_204": dial tcp 36.66.223.27:80: i/o timeout, Attempt 1
2024/03/10 16:53:46.558566 WARN RESTY Get "http://connectivitycheck.platform.hicloud.com/generate_204": dial tcp 1.37.34.208:80: i/o timeout, Attempt 2
2024/03/10 16:54:16.723258 WARN RESTY Get "http://connectivitycheck.platform.hicloud.com/generate_204": dial tcp 87.119.9.46:80: i/o timeout, Attempt 3
2024/03/10 16:54:46.987114 WARN RESTY Get "http://connectivitycheck.platform.hicloud.com/generate_204": dial tcp 119.46.76.15:80: i/o timeout, Attempt 4
2024/03/10 16:54:46.987152 ERROR RESTY Get "http://connectivitycheck.platform.hicloud.com/generate_204": dial tcp 119.46.76.15:80: i/o timeout
time="2024-03-10T16:54:46+08:00" level=error msg="Get \"http://connectivitycheck.platform.hicloud.com/generate_204\": dial tcp 119.46.76.15:80: i/o timeout"
time="2024-03-10T16:54:46+08:00" level=warning msg="LightsailMon Started"

**Comment by thank243** [comment]
no network.
