### ISSUE TITLE
出现异常，是怎么回事呢？有没有办法避免报错

### ISSUE THREAD

**Issue by elvischao** [thank243/lightsailMon#58]
LightsailMon (An AWS Lightsail monitor service that can auto change blocked IP.) 
Log level: warning  (Concurrent: 20)
time="2023-04-25T13:40:33+08:00" level=warning msg="LightsailMon Started"
LightsailMon (An AWS Lightsail monitor service that can auto change blocked IP.) 
Log level: warning  (Concurrent: 20)
time="2023-04-25T13:40:54+08:00" level=warning msg="LightsailMon Started"
time="2023-04-26T05:46:49+08:00" level=error msg="[AccessKeyID: *********] ***1.com:443 dial tcp4 13.250.111.216:443: i/o timeout"
time="2023-04-26T05:46:49+08:00" level=error msg="[AccessKeyID: *********] ***2.com:443 dial tcp4 3.1.218.7:443: i/o timeout"
time="2023-04-26T05:46:52+08:00" level=error msg="InvalidInputException: Some names are already in use: LightsailMon\n{\n  RespMetadata: {\n    StatusCode: 400,\n    RequestID: \"82ffe1cd-0aca-43fb-9b58-aaed4300a835\"\n  },\n  Code_: \"NameExists\",\n  Message_: \"Some names are already in use: LightsailMon\"\n}"
time="2023-04-26T05:46:52+08:00" level=error msg="[***1.com:443] Change node IP"
time="2023-04-26T05:46:52+08:00" level=error msg="[***2.com:443] Change node IP"
time="2023-04-26T05:46:55+08:00" level=error msg="InvalidInputException: Sorry, this static IP is not attached.\n{\n  RespMetadata: {\n    StatusCode: 400,\n    RequestID: \"63673724-cd9e-46a7-82f5-dc91a48a13da\"\n  },\n  Code_: \"InvalidAssociationID.NotFound\",\n  Message_: \"Sorry, this static IP is not attached.\"\n}"
time="2023-04-26T05:46:59+08:00" level=error msg="NotFoundException: The StaticIp does not exist: LightsailMon\n{\n  RespMetadata: {\n    StatusCode: 400,\n    RequestID: \"526b11a4-d26c-402a-ac82-fc2444a5c84e\"\n  },\n  Code_: \"DoesNotExist\",\n  Message_: \"The StaticIp does not exist: LightsailMon\"\n}"

**Comment by elvischao** [comment]
time="2023-04-26T05:46:55+08:00" level=error msg="InvalidInputException: Sorry, this static IP is not attached.\n{\n  RespMetadata: {\n    StatusCode: 400,\n    RequestID: \"63673724-cd9e-46a7-82f5-dc91a48a13da\"\n  },\n  Code_: \"InvalidAssociationID.NotFound\",\n  Message_: \"Sorry, this static IP is not attached.\"\n}"

**Comment by elvischao** [comment]
time="2023-04-26T05:46:59+08:00" level=error msg="NotFoundException: The StaticIp does not exist: LightsailMon\n{\n  RespMetadata: {\n    StatusCode: 400,\n    RequestID: \"526b11a4-d26c-402a-ac82-fc2444a5c84e\"\n  },\n  Code_: \"DoesNotExist\",\n  Message_: \"The StaticIp does not exist: LightsailMon\"\n}"

**Comment by thank243** [comment]
Delete all staticIP on your lightsail first and test again.

**Comment by elvischao** [comment]
OK.thanks,I will delete and test
